### ISSUE TITLE
Field Configuration

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/vue-formly#1]
The field configuration is different in the example then the official configuration (like angular-formly, ng-formly). We would like the configuration similar to them.

https://github.com/formly-js/ng2-formly/blob/master/src/core/components/formly.field.config.ts

**Comment by matt-sanders** [comment]
got it, thanks Mohammed, I'll start working on this soon

**Comment by matt-sanders** [comment]
Hey Mohammed, can you give me write access to vue-formly please? I just went to create a new branch and it said I don't have the correct access rights.

**Comment by mohammedzamakhan** [comment]
Can you try now?

**Comment by matt-sanders** [comment]
Nope, still nothing. I can't even edit anything through the web interface so it's not just something on my machine.

**Comment by mohammedzamakhan** [comment]
Can you instead fork this project and make a PR?

**Comment by mohammedzamakhan** [comment]
I changed some settings, can you try now?

**Comment by matt-sanders** [comment]
Perfect! thanks Mohammed.
