### ISSUE TITLE
vue-material layout rendering 

### ISSUE THREAD

**Issue by rodrigoAbril** [formly-js/vue-formly#11]
HI guys, 
We are creating all the forms in our web app with your nice component **vue-formly**,
We are also using vue-material and im trying to integrate them both ... So far I have encountered two problems and any help would be greatly apreciated. 

## 1. when trying to use the wrapper field to create a nice layout the vue-material tag doesn't get rendered.

```
{
          key: 'isValid',
          type: 'checkbox',
          wrapper: '<md-layout md-flex-xsmall="100" md-flex-small="50" md-flex="30"></md-layout>',
          templateOptions: {
            label: 'Se encuentra vigente'
          }
        },
        {
          key: 'validityOfThe',
          type: 'input',
          wrapper: '<md-layout md-flex-xsmall="100" md-flex-small="50" md-flex="33"></md-layout>',
          templateOptions: {
            label: 'Vigencia del'
          }
        }
```
`<md-layout>` never gets rendered as `<div class="md-layout"  ...>`, 

## 2. For the layout to work i need to add a container element for the columns

specifically a `<div class="md-layout">` as a first child of the formly generated `<fieldset>` that will work as a wrapper for all the fields, is there a way to do this correctly?

Should end up something like this
```
<form>
    <fieldset> <-- generated by formly
        <div class="md-layout"> <-- I need to add this some how
           //formly fields
        </div>
    </fieldset>
</form>
```

Again, any help would be greatly appreciated, if all goes right we are also thinking of forking this a vue-material-formly so any one can use it.

Regards

**Comment by matt-sanders** [comment]
@rodrigoAbril glad that you're enjoying vue formly! I'll take a look at these issues soon, but I'm pretty busy at the moment so it might not be until next week. I have an idea of how I'll fix number 1 but I'll just need to do sufficient unit testing before a release.

If you wanted these straight away you could always fork Vue Formly and add them yourself and submit a pull request. What I was thinking was that for issue 1 you could wrap the formly-form element in a `<component>` block. The default component could be a div and the `wrapper` element could be the name of the component and we could just dynamically bind the other props in a `wrapperProps` element. Maybe something like:

```js
// src/components/FormlyField.vue
<template>
   <component :is="wrapperElem" v-bind="field.wrapperProps">
      <component v-show="display" :is="type" :form.sync="form" :field="field" :model="model" :to="field.templateOptions"></component>
   </component>
</template>
<script>
export default {
... // all the other formlyField data
   computed: {
      wrapperElem(){ return this.field.wrapper || 'div'; }
   }
}
</script>
```

But like I said I'll hopefully make a more official release soon.

Issue 2 is also partially solved with the [custom layout directive](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/advanced_form_layouts.html). You could then do something like:
```js
<formly-form :fields="fields" :model="model" :form="form" :custom-layout="true">
   <div class="md-layout">
      <formly-field
	    :ref="field.key"
	    v-for="field in fields"
	    :form.sync="form"
	    :model.sync="model"
	    :field="field"
	    :key="'formly_'+field.key"></formly-field>
   </div>
</formly-form>
```

**Comment by rodrigoAbril** [comment]
@matt-sanders thank your very much for your help, 
I will test them out, and reply with my results.

**Comment by rodrigoAbril** [comment]
@matt-sanders 
#2 your solution worked perfectly.
#1 as Im implementing vue-material in this library I ended up creating all kinds of custom inputs, i found it was easier to control the responsive sizes utilizing the template options:
(please advice if you think what i did is silly)
```
//material switch
<template>
  <md-layout 
    :md-flex-xsmall="to.size.xs" 
    :md-flex-small="to.size.sm" 
    :md-flex="to.size.default">
    <md-switch
      v-model="model[field.key]"
      :name="field.key"
      :value="field.value"
      :disabled="to.disabled"
      :readonly="to.readonly"
      :class="[ to.inputType, to.wrapperClasses, {'formly-has-value': model[field.key], 
      'formly-has-focus': form[field.key].$active, 'has-error md-input-invalid has-danger': 
      hasError}]"
      @blur="onBlur"
      @focus="onFocus"
      @click="onClick"
      @change="onChange"
      @keyup="onKeyup"
      @keydown="onKeydown"
      v-formly-atts="to.atts">
      {{to.label}} <span v-if="field.required">*</span>
    </md-switch>
  </md-layout>
</template>
```
and i fill the parameters like this 
```
{
  key: 'isValid',
  type: 'switch',
  templateOptions: {
    label: 'Se encuentra vigente',
    size: {
      xs: '100',
      sm: '50',
      default: '40'
    }
  }
}

```

Regards and again thanks for your help

**Comment by matt-sanders** [comment]
Looks like a good solution to me! Especially if it's something you're going to be implementing on all fields. I'll close this as it looks like you're all sorted :)
