### ISSUE TITLE
 "key" is a reserved attribute and cannot be used as component prop

### ISSUE THREAD

**Issue by slava-the-human** [formly-js/vue-formly#13]
Hello! in vue@2.3.1  "key" is a reserved attribute and cannot be used as a component prop. I think rename will help.

**Comment by matt-sanders** [comment]
@slava-the-human Are you getting this error somewhere? Please make sure you're running the latest version, I think the only time I'm using `key` is in conjunction with `v-for` which is how it's intended. Cheers!

**Comment by slava-the-human** [comment]
Yes, I getting this error and I'm sure on latest version. You use 'key' in the fields to address field.

**Comment by matt-sanders** [comment]
Hmm, I'm not getting this error at all and I can't see anywhere that I use `:key` in an invalid way. You might be getting this error from somewhere else in your code. Unless you can highlight the issue with a code example or point out the offending line of code I'll close the issue.

Cheers!

**Comment by lcb931023** [comment]
@matt-sanders : I got this error as well when following the [documentation to create my own input type](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/creating_formly_fields.html).

vue@2.5.3, vue-formly@2.5.3
```
let myNewField = Vue.extend({
  props: ['form', 'key'],
  template: '<input type="text" v-model="form[key].value">'
});

Vue.$formly.addType('text', myNewField);
```

... is what the documentation suggests for creating custom input fields (without pulling in vue-formly-bootstrap as dependency). However this would trigger the error message in issue title, and accessing `this.key` within that component would return `undefined`

Looking through [vue-formly-bootstrap](https://github.com/formly-js/vue-formly-bootstrap/blob/master/src/fields/baseField.js#L4)'s code, it's not using `key` as a prop. Could that be why you aren't getting that error at all?

**Comment by matt-sanders** [comment]
@lcb931023 thanks for that, I see where the error is and have updated the documentation to reflect that. Instead of passing `form` and `key` as props, you should pass in `form`, `field`, and `model` and then you can use  `v-model="model[field.key]"`
