### ISSUE TITLE
Server-side code for validation?

### ISSUE THREAD

**Issue by COLABORATI** [formly-js/vue-formly#14]
Is there any server-side code for validation without having to duplicate the form definition work?

**Comment by matt-sanders** [comment]
Are you talking about for server side rendering or asynchronous validation? There is support for asynchronous validation and there are docs [here](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/validation.html).

**Comment by COLABORATI** [comment]
Rendering was not mentioned. I am looking for an elegant way how to communicate with a server side script that would need to validate the posted form data - I would like to use this library in a hostile environment (internet), so server side validation of input data is required. 

The asynchromous validation is one step into this direction - but of course I still do not want to trust JavaScript generated input - wouldn't it make sense to have kind of an post-submit error channel?

How do you handle that situatiuon? I assume that any kind of server side form input validation happens when anybody uses this form library - this is what I would like to red about. Of course building that  essential piece of security related code myself is always possible, but I am wondering why this very relevant thing is missing here? Also I like to use open source tools exactly for this reason: to have many eyes looking on security relevant code. 

Thanks!

**Comment by COLABORATI** [comment]
To keep it simple: I am looking for a full-request-cycle json-schema based form generator / validator - I see a few very interesting projects, like this one, which only deliver the frontend or the backend. It does of course make sense to keep frontend and backen related tasks decoupled, however I would expect better integration points.

**Comment by matt-sanders** [comment]
Sorry mate, I think this is a bit out of scope for how I see Formly going and also the time I currently have available to work on it. There are so many different ways that users would be connecting and sending data to their API's and I want to keep Formly as open as possible to handling different situations. If you want to extend it to handle what you're suggesting feel free to submit a PR that adds some better integration hooks for what you're suggesting and I'll think about including it into core. 
Cheers!
