### ISSUE TITLE
Pre-compile templates

### ISSUE THREAD

**Issue by sebastianmacias** [formly-js/vue-formly#17]
I'm using vue-formly/vue-formly-bootstrap on a Nuxt project (https://github.com/nuxt) and get this error on render:

[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

It works if I reference the compiler-included build in the web pack configuration of Nuxt like this:

build: { extend(config) { config.resolve.alias['vue'] = 'vue/dist/vue.common' } }

Is there another work-around ? like pre-compiling templates?

**Comment by matt-sanders** [comment]
Hmm, unfortunately not one that I'm aware of. I have been meaning to move all the templates to render functions for a little while now but have just been too busy so haven't got around to it yet. I'll also double check because I thought this would've happened when I run a build but apparently not. That might be the easiest solution.

**Comment by sebastianmacias** [comment]
Thanks for your reply, I'll keep watching this and the SSR Compatibility issues. In the meantime I will keep using the vue/dist/vue.common approach.

**Comment by imdanielpiva** [comment]
Hello, guys, is there any news about that issue?

**Comment by matt-sanders** [comment]
@imdanielpiva sorry not yet. I've been super busy. I'll try and take a look today

**Comment by imdanielpiva** [comment]
that's ok. I've been looking for a solution for that "handling vuex forms thing", and even thought about developing a plugin for vue-formly, a theme based on quasar-framework.org. thanks anyway, @matt-sanders, I'll keep watching!

**Comment by matt-sanders** [comment]
@imdanielpiva @sebastianmacias I've just made a release for Vue Formly ( 2.5.0 ) but am still working on Vue Formly Bootstrap. 

@imdanielpiva any plugins etc are welcome :) would love to see what you come up with!

**Comment by matt-sanders** [comment]
@imdanielpiva @sebastianmacias Vue Formly Bootstrap 2.5.0 has just been released and it contains support for SSR
