### ISSUE TITLE
Change/Replace Fields Dynamically?

### ISSUE THREAD

**Issue by zerkz** [formly-js/vue-formly#22]
I tinkered around with this (using the buefy plugin as well) and was able to get pretty far with a "dynamic" form system. 

I have a select input that basically supplements a different fields array to the formly-form `fields` property. 

All works well, except I'm getting validation errors inside of the field `validate()` method for some fields that have "required" set, particularly because they don't exist in the model. 

Error happens at this line when we try to check the length of the model[key] value. 
https://github.com/formly-js/vue-formly/blob/master/src/components/FormlyField.js#L49

![image](https://user-images.githubusercontent.com/1448099/32849738-b0c9dbec-c9f5-11e7-9cd6-21b5f0adb5a5.png)

Is what I'm trying to do a bad idea? Will I run into more issues then just this that I haven't foreseen?

Understand you might not be able to answer all questions. 

Here's a snippet of my code referencing my dynamic form system.

```
  watch: {
    selectedIssue : function(schema) {
      // this.form = {}; //clear form on selection..
      // this.model = {};
      this.fields = supportSchemas[schema];
    }
  },

  template: `
  <div class="box">
    <form>
      <h2>Support Form</h2>     
      <b-field>
            <b-select v-model="selectedIssue" placeholder="Select your issue.">
            <option
                    v-for="option in issueTypes"
                    :value="option.schema"
                    :key="option.label">
                    {{ option.label }}
                </option>
            </b-select>           
      </b-field>
      <formly-form :form="form" :model="model" :fields="fields"></formly-form>
      <b-field style="padding-top:10px;">        
          <button type="submit" class="button" style="width:100%;">Submit</button>          
      </b-field>
    </form>
  </div>`,
```

**Comment by matt-sanders** [comment]
Hey @zerkz you should be able to muster up something to the effect of what you're trying to achieve. I would wonder if maybe you need to assign the new field a blank value in the model first. In keeping with Vue thinking, the model or data must always be pre-defined, even if it's blank. So maybe, before you assign the fields, you could assign a new model with blank values. Try that and see if that works. I could also look into making sure it doesn't try and validate if there is no key present in the model, but it's probably better practice to set the model value anyway. make sense?

**Comment by zerkz** [comment]
thanks for the quick reply.

Isn't the `model` used for "default values"? I thought `form` was the "current state" of the form that is given whenever you submit?

**Comment by zerkz** [comment]
@matt-sanders additionally, is there a reason to having `validate()` called in the `created()` event of FormlyFields? I assume this is only to validate default values?

**Comment by matt-sanders** [comment]
Well, it depends on what version of Vue Formly you're using. If you're using 2.x ( which you probably are ) then the `form` attribute stores the current validation state of the form. The `model` represents the actual data. In that sense, it can be used to set the default data also, but this will b e updated as the form is changed. If you want to get a good understanding of how the data changes over time, just output the `form` and `model` attributes in a `<pre>` block or something and start changing values on the form. You'll see how it's reflected there.

`validate()` is called in the `created()` method to run an initial validation of the form. This sets up all the rules and populates the `form` attribute initially.

**Comment by zerkz** [comment]
Thanks, this helped alot. got it working! gonna close.
