### ISSUE TITLE
Updating fields

### ISSUE THREAD

**Issue by rodrigoAbril** [formly-js/vue-formly#25]
I can't to programmatically disable a form input, I've tried with a regular data variable, and a computed one, with no luck, is this even possible?

```
fields: [
{
    key: "name",
    type: "input",
    required: true,
    templateOptions: {
      disabled: this.formDisabled, // <<<------ update with api loaded data
      label: "Hora de visita",
    }
  },
]
````

**Comment by matt-sanders** [comment]
There's a couple of things that you need to fix up here. Firstly, it depends on what theme you're using. If you're using Vue Formly Bootstrap, you'll see that there's an `atts` attribute under the `templateOptions` section which defines attributes for the input, such as the `disabled` attribute. Secondly, the `data()` function on a vue component returns a state, it's not linked to itself, so if you have `this.formDisabled` and then update `formDisabled` it's not going to automatically update. You could either make `fields` a computed field, or you could set up a watcher on `formDisabled` to change the input. E.g.:

```
data(){
   fields: [
      {
          key: "name",
          type: "input",
          required: true,
          templateOptions: {
             atts: {
                  disabled: false
              },
              label: "Hora de visita",
          }
       },
   ]
},
watch: {
   formDisabled(disabled){
      this.fields[0].templateOptions.atts.disabled = disabled;
   }
}
```

Does that make sense?

**Comment by rodrigoAbril** [comment]
> There's a couple of things that you need to fix up here. Firstly, it depends on what theme you're using. If you're using Vue Formly Bootstrap, you'll see that there's an `atts` attribute under the `templateOptions` section which defines attributes for the input, such as the `disabled` attribute. Secondly, the `data()` function on a vue component returns a state, it's not linked to itself, so if you have `this.formDisabled` and then update `formDisabled` it's not going to automatically update. You could either make `fields` a computed field, or you could set up a watcher on `formDisabled` to change the input. E.g.:
> 
> ```
> data(){
>    fields: [
>       {
>           key: "name",
>           type: "input",
>           required: true,
>           templateOptions: {
>              atts: {
>                   disabled: false
>               },
>               label: "Hora de visita",
>           }
>        },
>    ]
> },
> watch: {
>    formDisabled(disabled){
>       this.fields[0].templateOptions.atts.disabled = disabled;
>    }
> }
> ```
> 
> Does that make sense?

It does make sense, sorry for Ignoring your reply for a couple of years ❤️
