### ISSUE TITLE
arrays of fields or field groups

### ISSUE THREAD

**Issue by donalmurtagh** [formly-js/vue-formly#29]
Support for an array of fields, or an array of field groups would be very useful. Without this feature, there is no obvious way to collect a list of values/objects if the length of the list is indeterminate. Here a couple of example use cases:

### 1. Array of Fields
For example, a form that allows the user to upload an unlimited number of images, each image would be stored base64 encoded inside an array.

### 2. Array of Field Groups
For example, if a user needs to enter the name, surname and date-of-birth of each of their children, this would be stored in the model as:

```json
[
  {"name": "John", "surname": "Doe", "dob": "1999-01-01"},
  {"name": "Jane", "surname": "Doe", "dob" "2000-01-01"}
]
```
A suggested implementation is to add [+] and [-] buttons to the form which would allow the user to add and remove an item in the array, or in the case of (2), clicking these buttons would add/remove a group of fields.

Support for this feature exists in [Angular Schema Form](https://github.com/json-schema-form/angular-schema-form) (an AngularJS declarative form library). The feature is documented [here](https://github.com/json-schema-form/angular-schema-form/blob/development/docs/index.md#array) and a demo is available [here](http://schemaform.io/examples/bootstrap-example.html) by choosing "Array" from the "Select Example" dropdown.

**Comment by matt-sanders** [comment]
thanks @donalmurtagh I'll take a look and see how I can implement this.

**Comment by donalmurtagh** [comment]
I don't know whether this is helpful, but this behaviour is also implemented by [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form). You can see it in action on the Arrays tab of their [demo page](https://mozilla-services.github.io/react-jsonschema-form/)

**Comment by anhoev** [comment]
any news ?

**Comment by matt-sanders** [comment]
Sorry, not yet, I've been so busy and just haven't had spare time to look at this. Feel free to PR if you want though

**Comment by matt-sanders** [comment]
@donalmurtagh see issue #39 which has a sample repeater field. While it's not natively supported by a vue-formly package, it's not too hard to implement. Gist is [here](https://gist.github.com/matt-sanders/d87db8917ef61c935cfe3d13958695fb)
