### ISSUE TITLE
Bootstrap Layouts

### ISSUE THREAD

**Issue by andyfensham** [formly-js/vue-formly#35]
I am trying to set up vue-formly to show my fields next to each other.  I am currently using angular formly and this works correctly there.  The fields show one below the other and does not show next to each other.

```
<template>
    <b-form-row>
        <b-col>
            <form @submit='doSomething'>
                <formly-form :form='form' :model='model' :fields='fields'>
                    <button>Submit</button>
                </formly-form>
            </form>
        </b-col>
    </b-form-row>
</template>
<script>
export default {
  data () {
    return {
      form: {},
      model: {
        name: '',
        sex: '',
        comments: ''
      },
      fields: [
        {
          key: 'name',
          type: 'input',
          wrapper: '<div class="col-sm-3 col-md-3 col-lg-3"></div>',
          templateOptions: {
            label: 'Your name'
          }
        },
        {
          key: 'sex',
          type: 'select',
          options: ['Male', 'Female'],
          wrapper: '<b-col sm="3" md="3" lg="3"></b-col>',
          templateOptions: {
            label: 'Sex'
          }
        },
        {
          key: 'comments',
          type: 'textarea',
          wrapper: '<b-col sm="3" md="3" lg="3"></b-col>',
          templateOptions: {
            label: 'Comments'
          }
        }
      ]
    }
  },
  methods: {
    doSomething: function () {}
  }
}
</script>
```

**Comment by matt-sanders** [comment]
Have you tried replacing the 'b-col' with a native element? At the moment it takes the wrapper string and inserts it as an element, so vue components won't be rendered as a component. This is something we're working on changing so that you can insert components and deeply nest elements.

**Comment by andyfensham** [comment]
Yes I tried.  Here is a static layout with the standard bootstrap classes with container, row, columns. I did a static grid below that that should replicate what I have and that works

`<template>
    <div class="container fluid">
        <div class="row">
            <form class="col" @submit='doSomething'>
                <formly-form class="col" :form='form' :model='model' :fields='fields'>
                    <button>Submit</button>
                </formly-form>
            </form>
        </div>            
        <div class="bv-example-row container">
            <div class="row">
                <div class="col-sm-4 col-md-4 col-lg-4">1 of 3</div>
                <div class="col-sm-4 col-md-4 col-lg-4">2 of 3</div>
                <div class="col-sm-4 col-md-4 col-lg-4">3 of 3</div>
            </div>
        </div>
    </div>

    
</template>
<script>
export default {
  data () {
    return {
      form: {},
      model: {
        name: '',
        sex: '',
        comments: ''
      },
      fields: [
        {
          key: 'name',
          type: 'input',
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Your name'
          }
        },
        {
          key: 'sex',
          type: 'select',
          options: ['Male', 'Female'],
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Sex'
          }
        },
        {
          key: 'comments',
          type: 'textarea',
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Comments'
          }
        }
      ]
    }
  },
  methods: {
    doSomething: function () {}
  }
}
</script>
<style>
    bv-example-row {
        background-color: rgba(86,61,124,.15);
        border: 1px solid rgba(86,61,124,.2);
    }
</style>

`

**Comment by andyfensham** [comment]
Here is one with native elements and classes.  I did a static layout just below that that works.  The Formly fields does not seem to fill the container.
``
<template>
    <div class="container fluid">
        <div class="row">
            <form class="col" @submit='doSomething'>
                <formly-form class="col" :form='form' :model='model' :fields='fields'>
                    <button>Submit</button>
                </formly-form>
            </form>
        </div>            
        <div class="bv-example-row container">
            <div class="row">
                <div class="col-sm-4 col-md-4 col-lg-4">1 of 3</div>
                <div class="col-sm-4 col-md-4 col-lg-4">2 of 3</div>
                <div class="col-sm-4 col-md-4 col-lg-4">3 of 3</div>
            </div>
        </div>
    </div>

    
</template>
<script>
export default {
  data () {
    return {
      form: {},
      model: {
        name: '',
        sex: '',
        comments: ''
      },
      fields: [
        {
          key: 'name',
          type: 'input',
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Your name'
          }
        },
        {
          key: 'sex',
          type: 'select',
          options: ['Male', 'Female'],
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Sex'
          }
        },
        {
          key: 'comments',
          type: 'textarea',
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Comments'
          }
        }
      ]
    }
  },
  methods: {
    doSomething: function () {}
  }
}
</script>
<style>
    bv-example-row {
        background-color: rgba(86,61,124,.15);
        border: 1px solid rgba(86,61,124,.2);
    }
</style>


``

**Comment by andyfensham** [comment]
Here is one with static classes. The fields does not seem to fill the container.
```

<template>
    <div class="container fluid">
        <div class="row">
            <form class="col" @submit='doSomething'>
                <formly-form class="col" :form='form' :model='model' :fields='fields'>
                    <button>Submit</button>
                </formly-form>
            </form>
        </div>            
        <div class="bv-example-row container">
            <div class="row">
                <div class="col-sm-4 col-md-4 col-lg-4">1 of 3</div>
                <div class="col-sm-4 col-md-4 col-lg-4">2 of 3</div>
                <div class="col-sm-4 col-md-4 col-lg-4">3 of 3</div>
            </div>
        </div>
    </div>

    
</template>
<script>
export default {
  data () {
    return {
      form: {},
      model: {
        name: '',
        sex: '',
        comments: ''
      },
      fields: [
        {
          key: 'name',
          type: 'input',
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Your name'
          }
        },
        {
          key: 'sex',
          type: 'select',
          options: ['Male', 'Female'],
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Sex'
          }
        },
        {
          key: 'comments',
          type: 'textarea',
          wrapper: '<div class="col-sm-4 col-md-4 col-lg-4"></div>',
          templateOptions: {
            label: 'Comments'
          }
        }
      ]
    }
  },
  methods: {
    doSomething: function () {}
  }
}
</script>
<style>
    bv-example-row {
        background-color: rgba(86,61,124,.15);
        border: 1px solid rgba(86,61,124,.2);
    }
</style>


```

**Comment by matt-sanders** [comment]
Hmm, everything seems to be working fine my end, see the screenshot below with the HTML open in the inspector and the fields displaying:
![screen shot 2018-06-07 at 7 15 48 am](https://user-images.githubusercontent.com/7637051/41060129-c1940cb8-6a22-11e8-8af3-0fc3f77cb7ab.png)

**Comment by andyfensham** [comment]
This is very strange.  Mine look exactly like yours

![image](https://user-images.githubusercontent.com/5065306/41086154-77d6399a-6a39-11e8-9629-8f49812bdcd1.png)

**Comment by andyfensham** [comment]
Please see this fiddle.  I stripped everything out and just had this items. Still in issue.

**Comment by andyfensham** [comment]
Please see this fiddle,  I stripped everything out. Still same.

[https://jsfiddle.net/afensham/ehvL98mp/1/](url)

**Comment by andyfensham** [comment]
I closed this by accident. But it should not be closed. I created a fiddle
with everything stripped out, but I still don't get it to show the fields
next to each other.

**Comment by matt-sanders** [comment]
I've managed to fix the issue, or at least figure out why it's not working as intended. It's not so much an issue with Vue Formly as it is a CSS issue. Vue Formly creates a fieldset element, and it looks like the cols don't work properly inside that. Probably some CSS issue, but I don't have time to dig into that too closely at the moment. Here's an updated version of your fiddle: https://jsfiddle.net/ehvL98mp/10/
