### ISSUE TITLE
Model initialization from server call

### ISSUE THREAD

**Issue by andyfensham** [formly-js/vue-formly#36]
I am initializing the model fields and default values from a server call in the created lifestyle hook. If I statically set the models before entering the component, it works E.g. model : {FirstName : '', LastName: ''}
But if I set this in the created function dynamically, there is no binding for my formly forms.

```
created: function() {
     axios.get('http://localhost/scadservices/api/tablesv2/' + this.TableId + '/minmetadata2.json?ViewId=' + this.ViewId, {crossdomain:true, withCredentials: true})
        .then((resp) => {
                this.metadata = resp.data
                console.log(JSON.parse(this.metadata.Form))
                var cols = this.metadata.Columns
                for (var key in cols) {
                    var obj = cols[key];
                    var colname = obj["ColumnName"]
                    this.model[colname] = ""
                }

                 this.fields = JSON.parse(this.metadata.Form)
        })
        .catch((err) => {
            console.log(err)
        })
  }
```

**Comment by matt-sanders** [comment]
hmm, this should work. What happens if you explicity set them, e.g. `this.$set(this.model, colName, '')` ?

**Comment by andyfensham** [comment]
Hi, If I explicitly set it like you did, it works, but not by this.model.FirstName = ''.  I will use it like proposed for now.  Thanks
