### ISSUE TITLE
Unable to run using Basic Example

### ISSUE THREAD

**Issue by mikeerickson** [formly-js/vue-formly#6]
- [ ] Create a new app using `vue-cli`
- [ ] Update `App.vue` with configuration (see below)
- [ ] Update `App.vue` with markup (see below)
- [ ] Produces error (see screenshot below)

```
<template>
  <div id="app">
    <form>
      <formly-form :form="form" :model="model" :fields="fields"></formly-form>
      <button type="submit">Submit</button>
    </form>
  </div>
</template>

<script>
import Vue from 'vue'
import Hello from './components/Hello'
import VueFormly from 'vue-formly'

Vue.use(VueFormly)

export default {
  name: 'app',
  components: {
    Hello
  },
  data () {
    return {
      form: {},
      model: {
        fname: '',
        lname: ''
      },
      fields: [
        {key: 'fname', type: 'input'},
        {key: 'lname', type: 'input'}
      ]
    }
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
```

![image](https://cloud.githubusercontent.com/assets/183153/23667068/971fbe74-0311-11e7-947a-e6f19daa42c1.png)

**Comment by matt-sanders** [comment]
Hey Mike

Have you installed Vue Formly Bootstrap or added any custom input types of your own? That solved the issue for me. It is mentioned in the documentation but I realised that it's not very clear so I'll update it.

Cheers

**Comment by mikeerickson** [comment]
@matt-sanders No, i figured that was just an "AddOn"

So all you did was install Vue Formly Bootstrap?

**Comment by matt-sanders** [comment]
Correct, you must install it and then include it in your project, but you just need to import and then use. See the example here: https://github.com/formly-js/vue-formly-bootstrap

**Comment by mikeerickson** [comment]
@matt-sanders Awesome, that did the trick!  I must have missed this in the docs 👍
