### ISSUE TITLE
Non standard way working with JSPM

### ISSUE THREAD

**Issue by charandas** [formly-js/vue-formly#7]
Not sure why the distributed bundle is not working with JSPM out of the box. Any ideas?

```
Vue.use(VueFormly.default);
Vue.use(VueFormlyBootstrap.default);
```

**Comment by matt-sanders** [comment]
Just took a wee look and it looks like I've bundled a few files by accident into the dist build. You could always just require the src file instead:
```js
var VueFormly = require('vue-formly/src/index.js');
```
However, you'll need a compiler as it does use imports etc. I'll make sure to remove those modules from the build and release a new version.

**Comment by matt-sanders** [comment]
Just FYI, I've found the issue, you can expect a new release tomorrow.

**Comment by charandas** [comment]
Great. Looking forward to the next release.

**Comment by charandas** [comment]
Yes, I got to trying it but the default property still comes out like that with my ES6 import.

I am using jspm / babel.

Also, were there other changes, it's silently failing to show forms. I haven't investigated it further. The previous versions were working when using the default property as shown above.

**Comment by matt-sanders** [comment]
Yep there were a couple of other features released there. Have you tried this with the latest release:
```js
import Vue from 'vue';
import VueFormly from 'vue-formly';
Vue.use(VueFormly);
```
or if you're using require
```js
var Vue = require('vue');
var VueFormly = require('vue-formly');
Vue.use(VueFormly);
```
Not sure why you're using `VueFormly.default`? 
If you have a full example can you reference that here, or even reference your github repo.

**Comment by charandas** [comment]
Sorry for the false report.

I was working on some other changes and forgot to retract them before
testing the new builds.

It still works. Let me paste what I am seeing after doing the regular
import.

**Comment by charandas** [comment]
![vue-formly-import-code](https://cloud.githubusercontent.com/assets/542168/25874921/c8f2d118-34e2-11e7-852f-a989f0375399.png)
![working-vue-formly](https://cloud.githubusercontent.com/assets/542168/25874923/cb6934c8-34e2-11e7-9dcc-2b52911335cd.png)

**Comment by charandas** [comment]
It doesn't work if I don't use the default property for obvious reasons. Not exactly sure why the dist files from your webpack build won't play with JSPM/Babel. It does have Rollup optimizations enabled, I can try disabling them, but a quick look shows they are not applying to formly plugin.

**Comment by matt-sanders** [comment]
Ah Ok, but it looks like the forms are rendering ok now? You'll need to include bootstrap css for it to look nice too. Vue Formly Bootstrap doesn't include them so that you can include your own custom build.

**Comment by matt-sanders** [comment]
If all that's required is that you need to use the `VueFormly.default` property then I might just leave it at that. I don't use JSPM very much and haven't had much request for it. I'll add it to the list of things to look at.

**Comment by charandas** [comment]
Ah ok. Thanks for the pointer on CSS. Yes, its working.

This issue was mainly to address the non-standard use I am having to resort to - aka `.default`. It might also be due to my using all this setup in Electron.

Sounds good. You can take a look in your leisure time.

By the way, the minified build got pushed in place of [unminified](https://github.com/formly-js/vue-formly/blob/master/dist/vue-formly.js) also.

**Comment by matt-sanders** [comment]
Great, sorry I think I misread your initial post. I'll take a look at that.

Oh thanks for pointing that out about the minified version. I'll take a look and rebuild. Anyone would think it was Monday the way today is going!
